SELECT
SYSDAT,
TRN_IE,
CTP_IE,
CTP,
LO,
COUNT(LIVE) AS  LIVEC, 
COUNT(MKT_OP) MKT_OPC,
COUNT(*) TRADES,
COUNT(ORI) ORIC,
COUNT(OFFS) OFFSC,
COUNT(TRF) TRFC

FROM

(
SELECT 
TO_CHAR(PC.M_DATE,'YYYY-MM-DD') SYSDAT,
CASE WHEN TRN.M_BINTERNAL = TRN.M_SINTERNAL THEN 'I' ELSE 'E' END TRN_IE,
CASE WHEN CTYP.M_REF = 16 THEN 'I' ELSE 'E' END CTP_IE, 
CASE WHEN TRN.M_BINTERNAL = TRN.M_SINTERNAL THEN RTRIM(BLE.M_DSP_LABEL)  ELSE RTRIM(CTP.M_DSP_LABEL) END CTP,
CASE WHEN TRN.M_TRN_GTYPE IN (49, 76, 100, 101, 136, 146) THEN 'LST' ELSE 'OTC' END LO,  
CASE WHEN TRN.M_TRN_STATUS = 'LIVE' THEN 1 ELSE NULL END LIVE, 
CASE WHEN TRN.M_TRN_STATUS = 'MKT_OP' THEN 1 ELSE NULL END MKT_OP,
CASE WHEN SUBSTR(TRN.M_GID,1,6) <> 'TDLPTE' THEN 1 ELSE NULL END ORI,
CASE WHEN SUBSTR(TRN.M_GID,8,3) = 'OFF' THEN 1 ELSE NULL END OFFS,
CASE WHEN SUBSTR(TRN.M_GID,8,3) = 'TRF' THEN 1 ELSE NULL END TRF

FROM TRN_HDR_DBF TRN
LEFT JOIN TRN_PC_DBF PC ON 1 = 1
LEFT JOIN TRN_PLIN_DBF PLIN ON TRN.M_INSTRUMENT = PLIN.M_REFERENCE
LEFT JOIN TRN_CPDF_DBF BLE ON TRN.M_BLENTITY = BLE.M_ID
LEFT JOIN TRN_CPDF_DBF SLE ON TRN.M_SLENTITY = SLE.M_ID
LEFT JOIN TRN_CPDF_DBF CTP ON TRN.M_COUNTRPART = CTP.M_ID
LEFT JOIN CTP_TYPES_DBF CTYP ON (CTP.M_ID = CTYP.M_CTN AND CTYP.M_REF = 16)
LEFT JOIN CONTRACT_DBF CNT ON TRN.M_CONTRACT = CNT.M_REFERENCE
LEFT JOIN SRC_MOD_DBF SRC ON CNT.M_SRC_MODULE = SRC.M_REFERENCE

WHERE 
(BLE.M_DSP_LABEL IN ('TDL','PTE') OR SLE.M_DSP_LABEL IN ('TDL','PTE'))
AND TRN.M_BINTERNAL <> TRN.M_SINTERNAL
AND COALESCE(CTYP.M_REF,0) = 0
AND TRN.M_TRN_STATUS <> 'DEAD'
AND TRN.M_TRN_EXP > PC.M_DATE
AND TRN.M_TRN_GTYPE NOT IN (1,2)
-- and rtrim(ctp.M_DSP_LABEL) = 'EMIRATES NBD PJSC, SINGAPORE BRANCH'
)

GROUP BY 
SYSDAT,
TRN_IE,
CTP_IE,
CTP,
LO

ORDER BY TRN_IE, CTP_IE, CTP, LO
