select M_NB TRD, M_TRN_GRP GRP, rtrim(M_TP_PFOLIO) PFL, 
rtrim(M_INSTRUMENT) INS, M_C_CUR_PL CUR,
M_TP_DIR BS, M_TP_LS LS, M_TP_NOM NOM, M_TP_QTY QTY, M_TP_PRICE PRC,
M_PL_NOT2 NOT2, M_PL_PC_NN2 PNL2, M_PL_ACC_N2

from CHECK_PL_REP
order by GRP, TRD

