DROP VIEW CMT_PLKEY_VW_DBF;

CREATE VIEW 
CMT_PLKEY_VW_DBF 
(
M_PLKEY, 
-- M_FGT,
M_ASSETTYPE,
M_ASSET,
M_PUBLI1,
M_FUTURE1,
M_FUTDES,
M_INDEX1,
M_UNDERL1,
M_CMIND1,
M_CMIDES,
M_QOT1,
M_CUR1,
M_UOQ1,
M_LOTSIZE,
M_PHYS1,
M_MATURITY1,
M_OPTMAT1,
M_VINTAG1,
M_OPT_EXP, 
M_QT_END,
M_DLV_FST, 
M_DLV_LST, 
M_SPLITMODE, 
M_NETMODE,
M_CMFUID 
) 
AS 

SELECT DISTINCT
plk.M_REFERENCE AS M_PLKEY,
-- trn.M_TRN_GTYPE AS FGT,
rtrim(atp.M_LABEL)   AS M_ASSETTYPE,
rtrim(ass.M_LABEL)   AS M_ASSET,
rtrim(pub.M_LABEL)   AS M_PUBLI1,
rtrim(fut.M_LABEL)   AS M_FUTURE1,
rtrim(fut.M_DESC)    AS M_FUTDES,
rtrim(ind.M_IND_LAB) AS M_INDEX1,
rtrim(und.M_IND_LAB) AS M_UNDERL1, 
rtrim(cmi.M_LABEL)   AS M_CMIND1,
rtrim(cmi.M_DESC)    AS M_CMIDES,
rtrim(qot.M_LABEL)   AS M_QOT1,
rtrim(qot.M_CURR)    AS M_CUR1,
rtrim(uoq.M_LABEL)   AS M_UOQ1,
coalesce(fut.M_QTY, cmi.M_LOTSIZE) AS M_LOTSIZE, 
rtrim(phy.M_LABEL)   AS M_PHYS1,
rtrim(fmat.M_LABEL)  AS M_MATURITY1,
rtrim(omat.M_LABEL)  AS M_OPTMAT1,
rtrim(vint.M_LABEL)  AS M_VINTAG,
omat.M_MATURITY      AS M_OPT_EXP,
fmat.M_QT_END        AS M_QT_END, 
fmat.M_ST_START      AS M_DLV_FST, 
fmat.M_ST_END        AS M_DLV_LST,
CASE
WHEN (fut.M_LISTED * fut.M_SPLT_RULE) = 0 THEN 'N'
WHEN fut.M_SPLT_RULE = 2 THEN 'T' ELSE 'E' END AS M_SPLITMODE,
CASE WHEN fut.M_NETTING_ALLOWED = 1 THEN 'Y' ELSE 'N' END AS M_NETMODE,
fut.M_REFERENCE AS M_CMFUID

FROM CMT_PLKEY1_DBF plk
-- LEFT JOIN TRN_HDR_DBF trn ON plk.M_REFERENCE = to_number(trim(trn.M_PL_KEY1),'9999999999') and trn.M_TRN_FMLY = 'COM'
LEFT JOIN CM_ASSET_DBF ass  ON plk.M_ASSET = ass.M_REFERENCE
LEFT JOIN CM_ATYPE_DBF atp  ON ass.M_TYPE = atp.M_REFERENCE
LEFT JOIN RT_INDEX_DBF ind  ON plk.M_INDEX = ind.M_INDEX
LEFT JOIN RT_INDEX_DBF und  ON plk.M_RT_UNDL = und.M_INDEX
LEFT JOIN CM_INDEX_DBF cmi  ON plk.M_UNDL = cmi.M_REFERENCE
LEFT JOIN CM_FUT_DBF   fut  ON plk.M_FUTURE = fut.M_REFERENCE and plk.M_FUTURE <> 0
LEFT JOIN CMC_QUOT_DBF qot  ON plk.M_QUOT = qot.M_REFERENCE and plk.M_QUOT <> 0
LEFT JOIN CM_MKT_DBF   pub  ON qot.M_PUBLI = pub.M_REFERENCE
LEFT JOIN CM_UNIT_DBF  uoq  ON qot.M_UNIT = uoq.M_REFERENCE
LEFT JOIN CM_PHYS_DBF  phy  ON plk.M_PRODUCT = phy.M_REFERENCE and plk.M_PRODUCT <> 0
LEFT JOIN CM_FMAT1_DBF fmat ON plk.M_FUT_MAT = fmat.M_REFERENCE and plk.M_FUT_MAT <> 0
LEFT JOIN CM_OMAT1_DBF omat ON plk.M_OPT_MAT = omat.M_REFERENCE and plk.M_OPT_MAT <> 0
LEFT JOIN CM_VINTAGE_DBF vint ON plk.M_VINTAGE = vint.M_REFERENCE and plk.M_VINTAGE <> 0
;
