select distinct
--val.M_INDEX2,
--rtrim(hdr.M_ORIGIN) SOURCE, 
case hdr.M_ORIGIN 
when 'CALENDAR'          then 'Calendars'
when 'CDS_GEN'           then 'Credit line generators'
when 'CF_GEN'            then 'Cap/Floor generators'
when 'COM'               then 'Com future & forward'
when 'COM_CF_GEN'        then 'Com asian generator'
when 'COM_CLR'           then 'Com cleared swap'
when 'COM_CLR_OPT'       then 'Com cleared asians'
when 'COM_FUT'           then 'Com future'
when 'COM_FWD'           then 'Com forward'
when 'COM_INDEX'         then 'Commodity indices'
when 'COM_LOCATIONS'     then 'Commodity locations'
when 'COM_OFUT_LST'      then 'Com listed future options'
when 'COM_PRODUCTS'      then 'Commodity products'
when 'COM_SWAP_GEN'      then 'Com swap generator'
when 'CTPRT'             then 'Counterparts'
when 'CURRENCY'          then 'Currencies'
when 'CUR_SWP_GEN'       then 'Currency swap generators'
when 'EQ_FUTURES'        then 'Equity futures'
when 'EQ OTC LISTED CTR' then 'Eq otc opt contracts'
when 'IRD_L_FUT'         then 'Long futures'
when 'IRD_S_FUT'         then 'Short futures'
when 'IRF OPT CTR'       then 'Irf opt contracts'
when 'ORDER_DURATION'    then 'Order duration'
when 'PL_INSTRUMENT'     then 'Pl Instrument'
when 'PORTFOLIO'         then 'Portfolios'
when 'SWP_GEN'           then 'Swap generators'
when 'VOLUME_PROF'       then 'Volume profiles'
else null end SRC_DESC,
/*
when 'X' then 'ADDR_TYPE'
when 'X' then 'Account'
when 'X' then 'Accounting sections'
when 'X' then 'Archiving columns'
when 'X' then 'Archiving groups'
when 'X' then 'BOND_TYPO'
when 'X' then 'Banks'
when 'X' then 'Basis conventions'
when 'X' then 'Bd opt contracts'
when 'X' then 'Bond generators'
when 'X' then 'Bond trading clauses'
when 'X' then 'Bonds'
when 'X' then 'Bonds finders'
when 'X' then 'Bonds security code'
when 'X' then 'Bonds/Short papers'
when 'X' then 'Brokers'
when 'X' then 'Brokers code'
when 'X' then 'Bsb generator'
when 'X' then 'CAP_TYPE'
when 'X' then 'CB_BONDS'
when 'X' then 'CFD generators'
when 'X' then 'CONF_LANG'
when 'X' then 'CS_TYPE'
when 'X' then 'Call deposits generators'
when 'X' then 'Callable bonds'
when 'X' then 'Callable bonds security code'
when 'X' then 'Cdons'
when 'X' then 'Classification'
when 'X' then 'Clearers'
when 'X' then 'Clearing'
when 'X' then 'Clients'
when 'X' then 'Com physical forward generator'
when 'X' then 'Commodity delivery terms'
when 'X' then 'Commodity physical routes'
when 'X' then 'Commodity units'
when 'X' then 'Commodity vintages'
when 'X' then 'Convertible bonds security code'
when 'X' then 'Countries'
when 'X' then 'Coupon bonds'
when 'X' then 'Credit baskets'
when 'X' then 'Credit baskets'
when 'X' then 'Credit counterparties'
when 'X' then 'Credit futures'
when 'X' then 'Credit futures security code'
when 'X' then 'Credit issuer codes'
when 'X' then 'Credit issuers'
when 'X' then 'Cusips'
when 'X' then 'Cut-off'
when 'X' then 'Cut-off full'
when 'X' then 'DDI futures'
when 'X' then 'DOC_TYPE'
when 'X' then 'Default details'
when 'X' then 'Default swap generators'
when 'X' then 'Diffusion: commodities (f)'
when 'X' then 'Diffusion: commodities (s)'
when 'X' then 'Diffusion: credit'
when 'X' then 'Diffusion: equities'
when 'X' then 'Diffusion: foreign exchange'
when 'X' then 'Diffusion: inflation'
when 'X' then 'Diffusion: interest rates'
when 'X' then 'Distribution groups'
when 'X' then 'EVT_TYPE'
when 'X' then 'EXT_IMPACT'
when 'X' then 'Entities'
when 'X' then 'Eq listed opt contracts'

when 'X' then 'Equities'
when 'X' then 'Equities & Baskets'
when 'X' then 'Equities & Baskets & Futures'
when 'X' then 'Equities & Baskets security co'
when 'X' then 'Equities security code'
when 'X' then 'Equity baskets'
when 'X' then 'Equity baskets security code'
when 'X' then 'Equity default swap generators'
when 'X' then 'Equity futures security code'
when 'X' then 'Equity swap generators'
when 'X' then 'Equity warrants'
when 'X' then 'Equity warrants security code'
when 'X' then 'Exchange traded funds security'
when 'X' then 'FO_VAL'
when 'X' then 'FRA generators'
when 'X' then 'First default basket'
when 'X' then 'Fixed price time series'
when 'X' then 'Flex fx indices
when 'X' then 'Flex inflation generators'
when 'X' then 'Flex rate indices'
when 'X' then 'Flex securities'
when 'X' then 'Funds'
when 'X' then 'Fx OTC contracts'
when 'X' then 'Fx listed contracts'
when 'X' then 'Groups'
when 'X' then 'ILLIQUID'
when 'X' then 'IRD warrants'
when 'X' then 'IRD warrants security code'
when 'X' then 'IRG generators'
when 'X' then 'IS_PAYER'
when 'X' then 'Inflation futures'
when 'X' then 'Inflation futures security code'
when 'X' then 'Interest rate indices'
when 'X' then 'Internal portfolios'
when 'X' then 'Issuer codes'
when 'X' then 'Issuers'
when 'X' then 'LB generators'
when 'X' then 'Listed maturities'
when 'X' then 'Loan generators'
when 'X' then 'Logical package'
when 'X' then 'MARGIN_TYP'
when 'X' then 'MAT_MODE'
when 'X' then 'MRG_MET'
when 'X' then 'Main classification'
when 'X' then 'Market data layout'
when 'X' then 'Markets'
when 'X' then 'ORD1_ACC'
when 'X' then 'Order template'
when 'X' then 'P2MEDIA'
when 'X' then 'P2PERIOD'
when 'X' then 'PACK_CONF'
when 'X' then 'PACK_VAL'
when 'X' then 'PREMIUM'
when 'X' then 'PRICING_IN'
when 'X' then 'Pl Instrument'
when 'X' then 'Ranking sources'
when 'X' then 'Rate conventions'
when 'X' then 'Rate indices'
when 'X' then 'Reference bond'
when 'X' then 'Repo generators'
when 'X' then 'Return swap generator'
when 'X' then 'Risk layout'
when 'X' then 'Risky total return swap generat'
when 'X' then 'SENS_BEN'
when 'X' then 'SETTLDIG'
when 'X' then 'STL_MTHD'
when 'X' then 'SWP_TYPE'
when 'X' then 'SW_SUBTYPE'
when 'X' then 'Sales'
when 'X' then 'Schedule generators'
when 'X' then 'Securities code contract classe'
when 'X' then 'Securities contract classes'
when 'X' then 'Seniorities'
when 'X' then 'Settlement convention'
when 'X' then 'Settlement methods'
when 'X' then 'Shares'
when 'X' then 'Shares Internal Code'
when 'X' then 'Shares Isin'
when 'X' then 'Shifters'
when 'X' then 'Shifters & Schedule generators'
when 'X' then 'Short futures security code'
when 'X' then 'Short papers'
when 'X' then 'Simple Equities security code'
when 'X' then 'Strategies'
when 'X' then 'Swap futures'
when 'X' then 'Swap futures  security code'
when 'X' then 'TRN_FMLY'
when 'X' then 'TRN_GRP'
when 'X' then 'Total return swap generators'
when 'X' then 'Trade category'
when 'X' then 'Traders'
when 'X' then 'Typologies'
when 'X' then 'Usages'
when 'X' then 'Users'
when 'X' then 'VIEWTYPE'
when 'X' then 'VOLSPD'
when 'X' then 'Vol future listed opt contracts'
when 'X' then 'Volume time series'
when 'X' then 'Warrant codes'
when 'X' then 'Warrant trading clauses'
when 'X' then 'collateral agreement'
when 'X' then 'collateral agreement category'
*/
rtrim(hdr.M_LABEL) LIST, 
hdr.M_INDEX LSTSEQ,
rtrim(val.M_VALUE) ITEM,
hdr.M_COMPLEMENTARY ALLBUT, hdr.M_EXCLUSIVE EXCLUSIV
from LST_PREFV_DBF val
left join LST_PREFH_DBF hdr on val.M_INDEX2 = hdr.M_INDEX
-- left join LST_PREFL_DBF lnk on val.M_INDEX2 = lnk.M_INDEX2

--where hdr.M_INDEX in (173,174,195,201,202)
order by SRC_DESC, LIST, ITEM