select 'Future' as M_TYPE,M_IND_LAB,M.M_LABEL as M_EXCHANGE, F.M_LABEL as M_FUTURE,MAT.M_LABEL as M_MATURITY,MAT.M_QT_END as M_EXP_DATE,MAT.M_LABEL as M_UND_MAT,MAT.M_QT_END as M_UND_EXP
from RT_INDEX_DBF I,CMC_QUOT_DBF Q, CM_MKT_DBF M, CM_FUT_DBF F, CM_FMAT1_DBF MAT
where --M_IND_LAB='SOYBEAN CBT NOV-14 USD/BU'
I.M_CATEGORY in (9,17)
and I.M_COM_QUOT=Q.M_REFERENCE and Q.M_PUBLI=M.M_REFERENCE and I.M_COM_FUT=F.M_REFERENCE and I.M_COM_MAT=MAT.M_REFERENCE
union all
select 'Option' as M_TYPE,M_IND_LAB,M.M_LABEL as M_EXCHANGE, F.M_LABEL as M_FUTURE,MAT.M_LABEL as M_MATURITY,MAT.M_MATURITY as M_EXP_DATE,UMAT.M_LABEL as M_UND_MAT,UMAT.M_QT_END as M_UND_EXP
from RT_INDEX_DBF I,CMC_QUOT_DBF Q, CM_MKT_DBF M, CM_FUT_DBF F, CM_OMAT1_DBF MAT, CM_FMAT1_DBF UMAT
where 
I.M_CATEGORY in (9,17) --M_IND_LAB='O SOYBEAN CBT MAY-15.MAY-15 USD/BU'
and I.M_COM_QUOT=Q.M_REFERENCE and Q.M_PUBLI=M.M_REFERENCE and I.M_COM_FUT=F.M_REFERENCE and I.M_COM_MAT=MAT.M_REFERENCE and MAT.M_UND_REF=UMAT.M_REFERENCE
order by 3,4,6
