select distinct
cnt.M_ROOT_REF ROOT, 
lnm.M_NB       TRN, 
typo.M_LABEL   TYPO, 
trn.M_TRN_STATUS STAT, 
lnm.M_PHASE PHS, 
lnm.M_LEG   CUSLEG, 
case 
lnm.M_TYPE 
when 0 then 'Payment date' 
when 1 then 'Fixing date' 
when 2 then 'Calculation start date' 
when 3 then 'Capital date' 
when 4 then 'Interest rate' 
when 5 then 'Interest flow' 
when 6 then 'Remaining capital payment flow' 
when 7 then 'Main strike' 
when 8 then 'Fixing' 
when 9 then 'Period main volatility' 
when 10 then 'Calculation end date' 
when 11 then 'Interest margin' 
when 12 then 'Secondary strike' 
when 13 then 'Period secondary volatility' 
when 14 then 'First fixing' 
when 15 then 'Exercise date' 
when 16 then 'Compounding rule' 
when 17 then 'Compounding mode' 
when 18 then 'Settlement date' 
when 19 then 'Settlement rate' 
when 20 then 'Settlement flow' 
when 21 then 'Settlement Calculation start date' 
when 22 then 'Settlement Calculation end date' 
when 23 then 'Adjustment rule' 
when 24 then 'Interest flow factor' 
when 25 then 'Capital calculation start date' 
when 26 then 'Capital calculation end date' 
when 27 then 'Capital payment date' 
when 28 then 'Capital payment flow' 
when 29 then 'Exercised' 
when 30 then 'Cliquet strike' 
when 31 then 'Cliquet secondary strike' 
when 32 then 'Amortizing annuity' 
when 33 then 'Barrier' 
when 34 then 'Capital payment flow' 
when 35 then 'Capital calc payment flow' 
when 36 then 'Interest reinvestment' 
when 37 then 'Interest rate plus dividend' 
when 38 then 'Interest flow plus dividend flow' 
when 39 then 'Indexation First interest' 
when 40 then 'Indexation Second interest' 
when 41 then 'Indexation First fixing' 
when 42 then 'Indexation Second fixing' 
when 43 then 'Indexation First margin' 
when 44 then 'Indexation Second margin' 
when 45 then 'Indexation First interest rate' 
when 46 then 'Indexation Second interest rate' 
when 47 then 'Indexation First initial capital' 
when 48 then 'Indexation Second initial capital' 
when 49 then 'Indexation First capital flow' 
when 50 then 'Indexation Second capital flow' 
when 51 then 'Indexation First final capital' 
when 52 then 'Indexation Second final capital' 
when 53 then 'Indexation First remaining capital' 
when 54 then 'Indexation Second remaining capital' 
when 55 then 'Indexation First interest date' 
when 56 then 'Indexation Second interest date' 
when 57 then 'Indexation First fixing date' 
when 58 then 'Indexation Second fixing date' 
when 59 then 'Indexation First margin date' 
when 60 then 'Indexation Second margin date' 
when 61 then 'Indexation First interest rate date' 
when 62 then 'Indexation Second interest rate date' 
when 63 then 'Indexation First initial capital date' 
when 64 then 'Indexation Second initial capital date' 
when 65 then 'Indexation First capital flow date' 
when 66 then 'Indexation Second capital flow date' 
when 67 then 'Indexation First final capital date' 
when 68 then 'Indexation Second final capital date' 
when 69 then 'Indexation First remaining capital date' 
when 70 then 'Indexation Second remaining capital date' 
when 71 then 'Rate factor' 
when 72 then 'Underlying first level' 
when 73 then 'Underlying second level' 
when 74 then 'Underlying first weight' 
when 75 then 'Underlying second weight' 
when 76 then 'Indexation First strike' 
when 77 then 'Indexation Second strike' 
when 78 then 'Indexation First strike date' 
when 79 then 'Indexation Second strike date' 
when 81 then 'Digital rate' 
when 82 then 'Indexation First dividends' 
when 83 then 'Indexation Second dividends' 
when 84 then 'Indexation First dividends date' 
when 85 then 'Indexation Second dividends date' 
when 86 then 'Indexation First tax credits' 
when 87 then 'Indexation Second tax credits' 
when 88 then 'Indexation First tax credits date' 
when 89 then 'Indexation Second tax credits date' 
when 90 then 'Exercise underlying start date' 
when 92 then 'Applied capital flow' 
when 93 then 'Quantity' 
when 98 then 'Non par repayment' 
when 99 then 'Initial capital payment date' 
when 100 then 'Final capital payment date' 
when 101 then 'Interest reinvestment no capital payment' 
when 102 then 'No capital payment' 
when 104 then 'Standard amount fx factor' 
when 105 then 'Indexation Second fixing end date' 
when 107 then 'Underlying first date' 
when 108 then 'Underlying second date' 
when 109 then 'Exercise start shifter' 
when 110 then 'Market last fixing' 
when 111 then 'Sales margin' 
when 112 then 'Applied remaining capital flow' 
when 113 then 'Range First bound' 
when 114 then 'Range Second bound' 
when 115 then 'Cumulative strike' 
when 116 then 'Flat correlation' 
when 118 then 'Ratchet First factor' 
when 119 then 'Ratchet Second factor' 
when 120 then 'Ratchet Third factor' 
when 121 then 'Ratchet First margin' 
when 122 then 'Ratchet Second margin' 
when 123 then 'Ratchet Third margin' 
when 124 then 'Exercise strike' 
when 125 then 'Base correlation inf' 
when 126 then 'Base correlation sup' 
when 127 then 'Compound correlation' 
when 128 then 'Second barrier' 
when 129 then 'Second digital rate' 
when 130 then 'Indexation First secondary strike' 
when 131 then 'Indexation Second Secondary strike' 
when 132 then 'Indexation First Secondary strike date' 
when 133 then 'Indexation Second Secondary strike date' 
when 134 then 'Market broken fixing' 
when 135 then 'Exercise Penalty fee rate' 
when 136 then 'Exercise Rental fee rate' 
when 137 then 'Exercise fee Capital mode' 
when 138 then 'Exercise fee End date mode' 
when 139 then 'Exercise fee End date specific' 
when 140 then 'Exercise fee End date shifter' 
when 142 then 'Range Sec. Index First bound' 
when 143 then 'Range Sec. Index Second bound' 
when 144 then 'Starting capital' 
when 145 then 'Compounded fixing' 
when 146 then 'No Amortizing' 
when 147 then 'Amortizing end date' 
when 148 then 'Quantity price' 
when 149 then 'Revolving event date' 
when 150 then 'Schedules limit date' 
when 151 then 'Decrease accrual Capital Flow' 
when 152 then 'Ex Dividend Period first date' 
when 153 then 'Ex Dividend Period last date' 
when 154 then 'Expiry Date' 
when 155 then 'Entry Date' 
when 156 then 'Last fixing date' 
when 157 then 'Fixing end' 
when 158 then 'Non indexed capital flow' 
when 159 then 'Exotic Barrier date' 
when 160 then 'Exotic Barrier' 
when 161 then 'Exotic Second barrier' 
when 162 then 'Exotic Barrier rebate' 
when 163 then 'Exotic Barrier fixing' 
when 164 then 'Implied correlation' 
when 165 then 'Accrual Capital Flow' 
when 166 then 'Flex numeric' 
when 167 then 'Flex date' 
when 168 then 'Flex string' 
when 169 then 'Flex menu' 
when 170 then 'Flex text' 
when 171 then 'Valuation shifter' 
when 172 then 'Fixing shifter' 
when 173 then 'Last valuation price' 
when 174 then 'Exercise penalty fee type' 
when 175 then 'Quantity fixing limit' 
when 176 then 'Quantity price fx factor' 
when 177 then 'Quantity payment date' 
when 178 then 'Basis Period Offset' 
when 179 then 'Indexation Second remaining capital first fixing' 
when 180 then 'Credit entity weight' 
when 181 then 'Credit entity status' 
when 182 then 'Basket computation type' 
when 183 then 'Nth to default' 
when 184 then 'Tranche down percentage' 
when 185 then 'Tranche up percentage' 
when 186 then 'Schedules end date' 
when 187 then 'Maturity Extension' 
when 188 then 'Fixing schedule end date' 
when 189 then 'Calculation schedule end date' 
when 190 then 'Fixing date without compounding' 
when 191 then 'Driving date' 
when 192 then 'Fixing non indexed' 
when 193 then 'First fixing non indexed' 
when 194 then 'Fixing end non indexed' 
when 195 then 'Interest ex-dividend date' 
when 196 then 'Capital ex-dividend date' 
when 197 then 'Fwd start log decomp rate' 
when 198 then 'Accrual rate or margin' 
when 199 then 'Accrual price' 
when 200 then 'Index rounding rule' 
when 201 then 'Index rounding decimals' 
when 202 then 'Index rebasement rounding rule' 
when 203 then 'Index rebasement rounding decimals' 
when 204 then 'Payment schedule limit date' 
when 205 then 'Event capital payment flow' 
when 206 then 'Shout shifter' 
when 208 then 'Premium schedule generator' 
when 210 then 'Event flow rate or margin' 
when 211 then 'Event flow price' 
when 212 then 'Event flow payment date' 
when 213 then 'Quantity trade date' 
when 214 then 'Specific discounting rate' 
when 215 then 'Forward start strike' 
when 216 then 'Credit stream model' 
when 217 then 'Denomination' 
when 218 then 'Underlying first spread' 
when 219 then 'Underlying second spread' 
when 220 then 'Underlying first power' 
when 221 then 'Underlying second power' 
when 222 then 'Barrier rebate date' 
when 224 then 'Range index' 
when 225 then 'Range second index' 
when 226 then 'Event flow fx rate' 
when 227 then 'Position price' 
when 228 then 'Position flow' 
when 229 then 'Additive interest flow' 
when 230 then 'Exercise mode' 
when 231 then 'Exercisable Nominal fraction' 
when 232 then 'Exercise default mode' 
when 233 then 'Exercisable default fraction' 
when 234 then 'Fixing lots' 
when 235 then 'Quantity event effective date' 
when 236 then 'Main index rounding rule' 
when 237 then 'Main index rounding decimals' 
when 238 then 'Unwind' 
when 239 then 'Main Original strike' 
when 240 then 'Logical Decomp. Flow' 
when 241 then 'Event payment flow fx' 
when 242 then 'Quantity rate or margin' 
when 243 then 'Event keep fixing date' 
when 244 then 'Indexation first recovery nominal' 
when 245 then 'Indexation second recovery nominal' 
when 246 then 'Indexation first date recovery nominal' 
when 247 then 'Indexation second date recovery nominal' 
when 248 then 'Indexation strike second end date' 
when 251 then 'Corporate action Capital flow' 
when 252 then 'Fail event: Theoretical date' 
when 253 then 'Fail event: Effective date' 
when 254 then 'Fail event: Security reference' 
when 255 then 'Fail event: Flow' 
when 256 then 'Fail event: Flow settlement date' 
when 257 then 'Corporate action: Split date' 
when 258 then 'Corporate action: Split quantity or nominal' 
when 259 then 'Corporate action: Bonus issue date' 
when 260 then 'Corporate action: Bonus issue quantity or nominal' 
when 261 then 'Corporate action: Reverse split date' 
when 262 then 'Corporate action: Reverse quantity or nominal' 
when 263 then 'Corporate action: Split price' 
when 267 then 'Corporate action: Split impact type' 
when 265 then 'Corporate action: Reverse split price' 
when 266 then 'Corporate action: Reverse split impact type' 
when 267 then 'Corporate action: Bonus issue impact type' 
when 268 then 'Corporate action: Split new capital date' 
when 269 then 'Corporate action: Reverse split new capital date' 
when 270 then 'Corporate action: Bonus issue new capital date' 
when 271 then 'Corporate action: Split security ratio' 
when 272 then 'Corporate action: Split underlying ratio' 
when 273 then 'Corporate action: Reverse split security ratio' 
when 274 then 'Corporate action: Reverse split underlying ratio' 
when 275 then 'First strike' 
when 276 then 'Second strike' 
when 277 then 'First strike date' 
when 278 then 'Second strike date' 
when 279 then 'Non rebased fixing' 
when 286 then 'Option dividend impact date' 
when 287 then 'Option dividend cash payment date' 
when 288 then 'Option dividend cash ex div date' 
when 289 then 'Option dividend cash record date' 
when 290 then 'Option dividend cash value' 
when 291 then 'Option dividend cash currency' 
when 292 then 'Option dividend cash position' 
when 293 then 'Option dividend security impact date' 
when 294 then 'Option dividend security effective date' 
when 295 then 'Option dividend security collateral effective date' 
when 296 then 'Option dividend security position' 
when 297 then 'Performance flow amendment' 
when 298 then 'Barrier second date' 
when 299 then 'Barrier second fixing' 
when 300 then 'Maturity extension open' 
when 301 then 'Dividend payment factor' 
when 302 then 'Dividend payment date' 
when 303 then 'Dividend flow' 
when 304 then 'Settled flow settlement date' 
when 305 then 'Mutual break mandatory' 
when 306 then 'Tax Credit payment factor' 
when 307 then 'Tax Credit payment date' 
when 308 then 'Tax Credit flow' 
when 309 then 'Fail maturity extension' 
when 310 then 'Default mutual break mandatory' 
when 311 then 'Barrier underlying first date' 
when 312 then 'Barrier underlying second date' 
when 313 then 'Barrier underlying first level' 
when 314 then 'Barrier underlying second level' 
when 315 then 'Barrier underlying first weight' 
when 316 then 'Barrier underlying second weight' 
when 317 then 'Barrier underlying first spread' 
when 318 then 'Barrier underlying second spread' 
when 319 then 'Barrier underlying first power' 
when 320 then 'Barrier underlying second power' 
when 321 then 'Indexation underlying first date' 
when 322 then 'Indexation underlying second date' 
when 323 then 'Indexation underlying first level' 
when 324 then 'Indexation underlying second level' 
when 325 then 'Indexation underlying first weight' 
when 326 then 'Indexation underlying second weight' 
when 327 then 'Indexation underlying first spread' 
when 328 then 'Indexation underlying second spread' 
when 329 then 'Indexation underlying first power' 
when 330 then 'Indexation underlying second power' 
when 331 then 'Secondary Original strike' 
when 332 then 'Barrier knocked' 
when 333 then 'Initial first FX fixing' 
when 334 then 'New Calculation Date' 
when 335 then 'Exercise second date' 
when 336 then 'Dividend capitalization fixing' 
when 337 then 'Additive capital payment flow' 
when 338 then 'Dividend capitalization flow' 
when 339 then 'Settlement upFront interest' 
when 340 then 'Settlement upFront discounted' 
when 341 then 'Settlement upFront payment date' 
when 342 then 'Non par repayment date' 
when 343 then 'Breakage flow' 
when 344 then 'Breakage flow date' 
when 345 then 'Breakage capital flow' 
when 346 then 'Residual rounding' 
when 347 then 'Optimal flow selected' 
when 348 then 'Barrier call spread' 
when 349 then 'Non indexed interest flow' 
when 350 then 'Non indexed intermediate capital flow' 
when 351 then 'Non indexed initial capital flow' 
when 352 then 'Non indexed final capital flow' 
else 'other' end CUSTOM, 
lnm.M_OP_DATE  OPSDAT, 
lnm.M_OFFSET   OFFSET, 
lnm.M_HOFFSET  HOFFSET, 
lnm.M_DATE     DAT, 
lnm.M_DOUBLE   NUM, 
lnm.M_CHOFFSET CHOFFSET, 
lnm.M_CHAR     CHARAC, 
lnm.M_EVENTID  EVTUID  

from RT_LNMOD_DBF lnm 
join TRN_HDR_DBF trn on lnm.M_NB = trn.M_NB 
join CONTRACT_DBF cnt on trn.M_CONTRACT = cnt.M_REFERENCE 
join TYPOLOGY_DBF typo on trn.M_TYPOLOGY = typo.M_REFERENCE 

where trn.M_TRN_STATUS <> 'DEAD' 
