select
M_MX_REF_JOB JOB,
M_NB TRN, 
rtrim(M_TRN_TYPE) FGT,
to_char(M_TP_DTEEXP,'YYYY-MM-DD') EXP,
M_TP_PRICE PRC, 
M_TP_STATUS2 STAT,
M_TP_IQTY QTY_SGD, M_TP_QTYEQ QTY_USD,
M_PL_CSFCP2, M_PL_CSFCP1,
M_PL_FMV2, M_PL_NFMV1,
(M_PL_CSFCP2-M_PL_CSFCP1) DIFF_CS,
(M_PL_FMV2-M_PL_NFMV1) DIFF_MV,
((M_PL_CSFCP2-M_PL_CSFCP1)+(M_PL_FMV2-M_PL_NFMV1)) DIFF_PL

from TRAF_TDLPTE_REP

order by M_TP_DTEEXP, M_TP_IQTY
