SELECT 
  BK1.M_LINK,
  HDR.M_NB,
  HDR.M_CONTRACT,
  HDR.M_GID,
  HDR.M_TRN_DATE,
  HDR.M_SYS_DATE,
  HDR.M_BTRADER,
  HDR.M_BRW_RTE1 AS PREMIUM,
  HDR.M_BRW_NOM1 AS QUANTITY,
  BK0.M_XISOPT AS ISOPT,
  BK0.M_XPRMPT AS PROMPT,
  BK0.M_XEXPIRY AS EXPIRY, 
  TRIM(M_XVSHIFT) AS VOL_SHIFT, 
  TRIM(M_XPSHIFT) AS PRICE_SHIFT,
  BK1.COUNTS,
  BK1.P1_STARTDATE, 
  BK1.P2_STARTDATE, 
  BK1.P3_STARTDATE, 
  BK1.P4_STARTDATE, 
  BK1.P5_STARTDATE, 
  BK1.P6_STARTDATE, 
  
  BK1.P1_ENDDATE ,
  BK1.P2_ENDDATE ,
  BK1.P3_ENDDATE ,
  BK1.P4_ENDDATE ,
  BK1.P5_ENDDATE ,
  BK1.P6_ENDDATE ,
  TRIM(D.M_PHYSICAL) AS M_PHYSICAL,
  TRIM(MTL.M_DESC) AS M_METAL,
  MTL.M_PUBL AS EXCHANGE,
  P.M_UNDERL1 AS UNDERLYING,
  PT.M_DSP_LABEL AS  COUNTERPART,
  EXT.M_LOCATION,
  EXT.M_TP_BUY
FROM RTBLOCK#RTBK0_DBF  BK0,
  (
    SELECT 
      M_LINK,
      COUNTS,
      MAX(P1_STARTDATE) AS P1_STARTDATE, 
      MAX(P2_STARTDATE) AS P2_STARTDATE,
      MAX(P3_STARTDATE) AS P3_STARTDATE,
      MAX(P4_STARTDATE) AS P4_STARTDATE,
      MAX(P5_STARTDATE) AS P5_STARTDATE,
      MAX(P6_STARTDATE) AS P6_STARTDATE,
      MAX(P1_ENDDATE) AS P1_ENDDATE,
      MAX(P2_ENDDATE) AS P2_ENDDATE,
      MAX(P3_ENDDATE) AS P3_ENDDATE,
      MAX(P4_ENDDATE) AS P4_ENDDATE,
      MAX(P5_ENDDATE) AS P5_ENDDATE,
      MAX(P6_ENDDATE) AS P6_ENDDATE
    FROM
      (
        SELECT 
          M_LINK,
          PROWS,
          COUNTS,
          CASE WHEN PROWS=1 THEN STARTDATE ELSE NULL END P1_STARTDATE,
          CASE WHEN PROWS=2 THEN STARTDATE ELSE NULL END P2_STARTDATE,
          CASE WHEN PROWS=3 THEN STARTDATE ELSE NULL END P3_STARTDATE,
          CASE WHEN PROWS=4 THEN STARTDATE ELSE NULL END P4_STARTDATE,
          CASE WHEN PROWS=5 THEN STARTDATE ELSE NULL END P5_STARTDATE,
          CASE WHEN PROWS=6 THEN STARTDATE ELSE NULL END P6_STARTDATE,
          
          CASE WHEN PROWS=1 THEN ENDDATE ELSE NULL END P1_ENDDATE,
          CASE WHEN PROWS=2 THEN ENDDATE ELSE NULL END P2_ENDDATE,
          CASE WHEN PROWS=3 THEN ENDDATE ELSE NULL END P3_ENDDATE,
          CASE WHEN PROWS=4 THEN ENDDATE ELSE NULL END P4_ENDDATE,
          CASE WHEN PROWS=5 THEN ENDDATE ELSE NULL END P5_ENDDATE,
          CASE WHEN PROWS=6 THEN ENDDATE ELSE NULL END P6_ENDDATE
         FROM
         (
        SELECT 
          BK1.M_LINK,
          ROW_NUMBER () OVER (PARTITION BY M_LINK ORDER BY M_LINK ) AS PROWS,
          COUNT(BK1.M_XPSTART) OVER (PARTITION BY M_LINK) AS COUNTS,
          BK1.M_XPSTART AS STARTDATE, 
          BK1.M_XPEND AS ENDDATE 
        FROM  
          RTBLOCK#RTBK1_DBF BK1
          ORDER BY M_LINK,M_XPSTART
        )
      )
    GROUP BY M_LINK,COUNTS
  )BK1,
  RTBLOCK#RTBKSKL_DBF BKS,
  TRN_HDR_DBF HDR,
  CMT_DLVEXT_DBF D,
  CMT_PLKEYEXT3_DBF P,
  TRAF_PL_COM_DESC_DBF MTL,
  TRN_CPDF_DBF PT,
  HDREXT_VW_DBF EXT
WHERE HDR.M_NB=BKS.M_INT_NB
AND BK0.M_INT_NB=BKS.M_BK_INT_N
AND BK1.M_LINK =BK0.M_LINK
AND HDR.M_TYPOLOGY=1402
AND HDR.M_NB=D.M_NB(+)
AND HDR.M_NB=MTL.M_NB(+)
AND D.M_PHYSICAL IS NOT NULL
AND HDR.M_PL_KEY1   =P.M_PLKEY(+)
AND HDR.M_COUNTRPART=PT.M_ID
AND HDR.M_NB=EXT.M_TNB
AND BK0.M_XEXPIRY=@EXPIRY:D