SELECT 
HDR.M_NB AS TRN,
HDR.M_CONTRACT AS CNT,
HDR.M_GID AS GID,
HDR.M_TRN_DATE AS DAT_TRN,
HDR.M_SYS_DATE AS DAT_SYS,
RTRIM(HDR.M_TRN_STATUS) AS STATUS,
HDR.M_BTRADER AS TRADER,
RTRIM(INIP.M_CHAR_VAL) AS SRC_PFL,
RTRIM(INIC.M_CHAR_VAL) AS DST_PFL,
PT.M_DSP_LABEL AS  COUNTERPART,
MTL.M_PUBL AS EXCHANGE,
P.M_UNDERL1 AS UNDERLYING,
TRIM(MTL.M_DESC) AS METAL,
TRIM(D.M_PHYSICAL) AS PHYSICAL,
EXT.M_LOCATION AS LOCATION,
EXT.M_TP_BUY AS BS,
CASE WHEN HDR.M_BRW_CP='C' THEN 'Call' WHEN HDR.M_BRW_CP='P' THEN 'Put' ELSE '' END AS KIND, 
CASE WHEN BK0.M_XISOPT='True' THEN 'Option' ELSE 'Obligation' END AS ISOPT,
HDR.M_BRW_RTE1 AS PREMIUM,
CASE WHEN RTRIM(MTL.M_PUBL) = 'LME' THEN HDR.M_BRW_NOM1/25 ELSE  HDR.M_BRW_NOM1 END AS LOTS,
HDR.M_BRW_NOM1 AS QUANTITY,
BK0.M_XPRMPT AS DAT_PROMPT,
BK0.M_XEXPIRY AS DAT_EXP, 
-- UDF.M_BP_EXP_TIM AS TIM_EXP,
BK1.M_XPSTART AS DAT_START, 
BK1.M_XPEND AS DAT_END ,
TRIM(M_XPSHIFT) AS PRC_SHIFT,
TRIM(M_XVSHIFT) AS VOL_SHIFT
  
FROM  
RTBLOCK#RTBK0_DBF  BK0,
RTBLOCK#RTBK1_DBF BK1,
RTBLOCK#RTBKSKL_DBF BKS,
TRN_HDR_DBF HDR,
CMT_DLVEXT_DBF D,
CMT_PLKEYEXT3_DBF P,
TRAF_PL_COM_DESC_DBF MTL,
TRN_CPDF_DBF PT,
HDREXT_VW_DBF EXT,
NP_IDATA_DBF INIP,
NP_IDATA_DBF INIC,
TRN_EXT_DBF EXTRA,
(select distinct M_TRADE_REF,  max(M_VERSION) as M_VERSN_LAST from TRN_EXT_DBF group by M_TRADE_REF) EXT_MAX,
  TABLE#DATA#DEALCOM_DBF UDF

WHERE  
HDR.M_NB=BKS.M_INT_NB
AND BK0.M_INT_NB=BKS.M_BK_INT_N
AND BK1.M_LINK =BK0.M_LINK
AND HDR.M_TYPOLOGY=1402
AND HDR.M_NB=D.M_NB(+)
AND HDR.M_NB=MTL.M_NB(+)
AND D.M_PHYSICAL IS NOT NULL
AND HDR.M_PL_KEY1   =P.M_PLKEY(+)
AND HDR.M_COUNTRPART=PT.M_ID
AND HDR.M_NB=EXT.M_TNB
AND HDR.M_NB=INIP.M_SNAP_ID AND RTRIM(INIP.M_LABEL)='Portfolio (input)'
AND HDR.M_NB=INIC.M_SNAP_ID AND RTRIM(INIC.M_LABEL)='Counterpart (input)'
AND HDR.M_NB = EXTRA.M_TRADE_REF
AND EXTRA.M_UDF_REF = UDF.M_NB(+)
AND EXTRA.M_TRADE_REF = EXT_MAX.M_TRADE_REF  
AND BK0.M_XEXPIRY=@EXPIRY:D
--AND
--  HDR.M_NB=10294958
