select
M_MX_REF_JOB JOB,
M_TRN_GTYPE FGT,
rtrim(M_INSTRUMENT) INS,
M_TP_PFOLIO PFL,
sum(M_PL_MV_NFI2) MV_NFI2,
sum(M_PL_FP_NFI2) FP_NFI2,
sum(M_PL_PC_NFI2) PC_NFI2,
sum(M_PL_MV_FIN2) MV_FIN2,
sum(M_PL_FP_FIN2) FP_FIN2,
sum(M_PL_PC_FIN2) PC_FIN2,
sum(M_PL_GEPL2) GE2,
sum(M_PL_NEPL2) NE2,
count(*) OCC

from TDLPTE_PNL_REP
group by M_MX_REF_JOB, M_TRN_GTYPE, M_INSTRUMENT, M_TP_PFOLIO

order by JOB, INS, PFL

/*
select
M_MX_REF_JOB,
M_TRN_GTYPE FGT,
M_INSTRUMENT INS,
M_TP_PFOLIO PFL,
M_PL_MV_NFI2 MV_NFI2,
M_PL_FP_NFI2 FP_NFI2,
M_PL_PC_NFI2 PC_NFI2,
M_PL_MV_FIN2 MV_FIN2,
M_PL_FP_FIN2 FP_FIN2,
M_PL_PC_FIN2 PC_FIN2,
rownum
from TDLPTE_PNL_REP
*/
