select * from 

(
select trim(M_NAME) as M_FORMULA, 
(trim(UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(M_BODY, 2000, 1)))     || trim(UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(M_BODY, 2000, 2000))))  as M_MSL_A,
(trim(UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(M_BODY, 2000, 4000)))  || trim(UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(M_BODY, 2000, 6000))))  as M_MSL_B,
(trim(UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(M_BODY, 2000, 8000)))  || trim(UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(M_BODY, 2000, 10000)))) as M_MSL_C,
(trim(UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(M_BODY, 2000, 12000))) || trim(UTL_RAW.CAST_TO_VARCHAR2(DBMS_LOB.SUBSTR(M_BODY, 2000, 14000)))) as M_MSL_D

from NPD_MSL_DBF
)

where 
   upper(M_MSL_A) like '%ENTITY%' 
or upper(M_MSL_B) like '%ENTITY%'
or upper(M_MSL_C) like '%ENTITY%'
or upper(M_MSL_D) like '%ENTITY%'

order by M_FORMULA;
