update TRN_ACSC_DBF set M_DESC = 'Chemicals (Oil)' where rtrim(M_LABEL) = '1113';
update TRN_ACSC_DBF set M_DESC = 'Fuel'            where rtrim(M_LABEL) = '1115';
update TRN_ACSC_DBF set M_DESC = 'Latam Projects'  where rtrim(M_LABEL) = '1126';
update TRN_ACSC_DBF set M_DESC = 'STF - Oil'       where rtrim(M_LABEL) = '1127';
update TRN_ACSC_DBF set M_DESC = 'Oil Derivatives' where rtrim(M_LABEL) = '1151';
update TRN_ACSC_DBF set M_DESC = 'Shipping'        where rtrim(M_LABEL) = '1171';
update TRN_ACSC_DBF set M_DESC = 'Mexico Domestic' where rtrim(M_LABEL) = '1212';
update TRN_ACSC_DBF set M_DESC = 'Gasoline Rack'   where rtrim(M_LABEL) = '1213';
update TRN_ACSC_DBF set M_DESC = 'Other(Downstr)'  where rtrim(M_LABEL) = '1214';
update TRN_ACSC_DBF set M_DESC = 'Quantum Enery'   where rtrim(M_LABEL) = '1314';
update TRN_ACSC_DBF set M_DESC = 'Sawtooth'        where rtrim(M_LABEL) = '1316';
update TRN_ACSC_DBF set M_DESC = 'Other(Inv Oil)'  where rtrim(M_LABEL) = '1318';
update TRN_ACSC_DBF set M_DESC = 'Greenergy'       where rtrim(M_LABEL) = '1322';
update TRN_ACSC_DBF set M_DESC = 'Rhone Energy'    where rtrim(M_LABEL) = '1323';
update TRN_ACSC_DBF set M_DESC = 'Puma Non Trdng'  where rtrim(M_LABEL) = '1411';
update TRN_ACSC_DBF set M_DESC = 'Cobalt(RM)'      where rtrim(M_LABEL) = '2220';
update TRN_ACSC_DBF set M_DESC = 'Other(Iron Ore)' where rtrim(M_LABEL) = '2314';
update TRN_ACSC_DBF set M_DESC = 'Lobito Atl Corr' where rtrim(M_LABEL) = '2435';
update TRN_ACSC_DBF set M_DESC = 'Impala Colombia' where rtrim(M_LABEL) = '2914';
update TRN_ACSC_DBF set M_DESC = 'Puma Infra'      where rtrim(M_LABEL) = '2915';
update TRN_ACSC_DBF set M_DESC = 'Corp (Loan)'     where rtrim(M_LABEL) = '3181';
