update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Aluminium (RM)'  where M_RMDLAB = 'Aluminium(RM)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Blister (RM)'    where M_RMDLAB = 'Blister(RM)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Chemicals (Oil)' where M_RMDLAB = 'Chemical (Oil)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Chemicals (Oil)' where M_RMDLAB = 'Chemical(Oil)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Cobalt(RM)'      where M_RMDLAB = 'Cobalt (RM)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Copper (Conc)'   where M_RMDLAB = 'Copper(Conc)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Corp (Loan)'     where M_RMDLAB = 'Corp (Loans)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Corp (GCM)'      where M_RMDLAB = 'Corp(GCM)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Crude'           where M_RMDLAB = 'CRUDE';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Distillates'     where M_RMDLAB = 'DISTILLATES';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Fuel'            where M_RMDLAB = 'FUEL OIL';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Fuel'            where M_RMDLAB = 'Fuel Oil';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Gasoline'        where M_RMDLAB = 'GASOLINE';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Gold (RM)'       where M_RMDLAB = 'Gold(RM)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Latam Projects'  where M_RMDLAB = 'Latam Desk';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Latam Projects'  where M_RMDLAB = 'LATAM PROJECTS';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Lead (Conc)'     where M_RMDLAB = 'Lead(Conc)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Lead (RM)'       where M_RMDLAB = 'Lead(RM)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Naphtha'         where M_RMDLAB = 'NAPHTHA';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Nat Gas'         where M_RMDLAB = 'NAT GAS';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Nickel (Conc)'   where M_RMDLAB = 'Nickel(Conc)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Nickel (RM)'     where M_RMDLAB = 'Nickel(RM)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Other (Oil)'     where M_RMDLAB = 'OTHER (OIL)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Other (Oil)'     where M_RMDLAB = 'Other(Oil)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Other (Coal)'    where M_RMDLAB = 'Other(Coal)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Other(Iron Ore)' where M_RMDLAB = 'Other (IronOre)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Puma Bitumen'    where M_RMDLAB = 'PUMA BITUMEN';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Puma East'       where M_RMDLAB = 'PUMA EAST';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Puma West'       where M_RMDLAB = 'PUMA WEST';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Silver (RM)'     where M_RMDLAB = 'Silver(RM)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Steel (RM)'      where M_RMDLAB = 'Steel';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Zinc (Conc)'     where M_RMDLAB = 'Zinc(Conc)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'Zinc (RM)'       where M_RMDLAB = 'Zinc(RM)';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'STF - Oil'       where M_RMDLAB = 'OIL STF';
update TABLE#DATA#PORTFOLI_DBF set M_RMDLAB = 'CED Shanghai'    where M_RMDLAB = '2422';
