SELECT 
USR.M_LABEL as USER_NO
,USR.M_DESC as USER_NAME
,USR.M_CODE as USER_GROUP
--,USR.M_FULL_NAME
, CASE WHEN LENGTH(TECH.USR_LABEL)> 0 THEN 'TRUE' ELSE 'FALSE' END as USER_TECHNICAL 
FROM
MX_USER_DBF USR
LEFT OUTER JOIN 
(SELECT distinct
A.M_LABEL AS USR_LABEL
FROM
MX_USER_DBF A
LEFT OUTER JOIN MX_USER_POLICY_DBF P ON A.M_POLICY_ID = P.M_REFERENCE
LEFT OUTER JOIN MX_USER_GROUP_DBF B ON A.M_REFERENCE=B.M_USER_ID
LEFT OUTER JOIN MX_GROUP_DBF C ON B.M_GROUP_ID=C.M_REFERENCE
left outer join TRN_GRPD_DBF GRPD on rtrim(GRPD.M_LABEL) = rtrim(C.M_LABEL)
left join ROLE_DBF ROL on ROL.M_REFERENCE=GRPD.M_ROLE
where
A.M_DESC like 'Technical%' or ROL.M_LABEL = 'Technical') TECH ON TECH.USR_LABEL = USR.M_LABEL