select 
-- M_NB, M_TP_GID, M_CNTLEVTL2, M_TP_STATUS2,
M_TRN_FMLY FML, M_TRN_GRP GRP, 
M_INSTRUMENT INS, M_C_CUR_PL CUR,
M_TP_CMCMAT MAT, 
to_char(M_TP_DTEEXP,'YYYY-MM-DD') EXP,
sum(M_PL_GEPL2) GEPL2, 
sum(M_PL_NEPL2) NEPL2, 
sum(M_PL_FE_FIN2) FEFI2, 
count(*)

from TRAF_TDLPTE_REP 
where M_MX_REF_JOB = 92393

group by 
M_TRN_FMLY, M_TRN_GRP, 
M_INSTRUMENT, M_C_CUR_PL, 
M_TP_CMCMAT, M_TP_DTEEXP

order by FML, GRP, INS, CUR, EXP, MAT 