SELECT
pnl.M_TP_PFOLIO AS PFL,
pnl.M_CONTRACT AS CNT,
-- pnl.M_CNT_VS2 AS VS,
-- pnl.M_PACKAGE AS PCK,
pnl.M_NB AS TRN,
to_char(pnl.M_TP_DTETRN,'YYYY-MM-DD') AS TRNDAT,
rtrim(pnl.M_CNT_TYPO) AS TYPO,
rtrim(pnl.M_INSTRUMENT) AS INS,
trim(pnl.M_TP_TEN) AS TENOR,
to_char(pnl.M_TP_DTEEXP,'YYYY-MM-DD') AS EXP,
pnl.M_TP_PRICE AS PRC,
rtrim(pnl.M_TP_COQ) AS CUR,
rtrim(pnl.M_TP_UOQ) AS UOM,
pnl.M_TP_NOM0 AS NOM0,
pnl.M_TP_NOM1 AS NOM1,
to_char(pnl.M_VAL_DAT2,'YYYY-MM-DD') AS VAL_DAT,
pfl.M_LE_ACCCUR AS LE_CUR,
pnl.M_C_CUR_PL AS PL_CUR,
pnl.M_ACC_CUR AS ACC_CUR,
pnl.M_MP_FXSPD2 AS MP_FXSPD2,
pnl.M_MP_FXSPDE AS MP_FXSPDE,
pnl.M_PL_ACC_N2 PL_ACC_N2,
pnl.M_PL_PC_NC2 AS PL_PC_NC2,
pnl.M_PL_PC_NCE AS PL_PC_NCE,
(pnl.M_PL_PC_NC2 - pnl.M_PL_PC_NCE) AS PL_PC_DIFF

FROM TRF_PL_RVL_REP pnl
LEFT JOIN PORTFOLIO_REP pfl ON RTRIM(pnl.M_TP_PFOLIO) = RTRIM(pfl.M_LABEL)

WHERE 
-- pnl.M_TP_PFOLIO = 'MCEX OMU PTEI'
pnl.M_NB = 13427501
-- AND pnl.M_TP_DTETRN=@TRADE_DT:D
 
ORDER BY pnl.M_NB