 
SELECT
trn.M_NB                TRN,
RTRIM(trn.M_TRN_FMLY)   FML,
RTRIM(typo.M_LABEL)     TYPO,
RTRIM(plin.M_DSP_LABEL) INS,
RTRIM(phy.M_LABEL)      PHY,
RTRIM(phytyp.M_LABEL)   PHYTYP,
RTRIM(phylut.M_PHYLAB)  PHYRMD,
CASE WHEN trn.M_BINTERNAL = trn.M_SINTERNAL THEN 'I' ELSE 'E' END IE,
RTRIM(trn.M_COMMENT_BS) BS,
RTRIM(pflsrc.M_LABEL)   SRC_PFL,
RTRIM(pfldst.M_LABEL)   DST_PFL,
RTRIM(ctp.M_DSP_LABEL)  CTP,
CASE WHEN trn.M_BINTERNAL = 'Y' THEN 'PFL' ELSE 'CTP' END B_PFLNAT,
RTRIM(udfb.M_STREAM) B_PFLSTM,
RTRIM(udfb.M_PTFCAT) B_PFLCAT,
RTRIM(trn.M_BPFOLIO) B_PFLLAB,
RTRIM(udfb.M_RMDCOD) B_RMDCOD,
RTRIM(udfb.M_RMDLAB) B_RMDLAB,
RTRIM(udfb.M_RMDPHY) B_RMDPHY,
RTRIM(udfb.M_RMDFLG) B_RMDFLG,
CASE WHEN trn.M_SINTERNAL = 'Y' THEN 'PFL' ELSE 'CTP' END S_PFLNAT,
RTRIM(udfb.M_STREAM) S_PFLSTM,
RTRIM(udfs.M_PTFCAT) S_PFLCAT,
RTRIM(trn.M_SPFOLIO) S_PFLLAB,
RTRIM(udfs.M_RMDCOD) S_RMDCOD,
RTRIM(udfs.M_RMDLAB) S_RMDLAB,
RTRIM(udfs.M_RMDPHY) S_RMDPHY,
RTRIM(udfs.M_RMDFLG) S_RMDFLG,
CASE 
WHEN trn.M_COMMENT_BS = 'B' THEN COALESCE(udfcur.M_PL_ASSIG, udfscf.M_PL_ASSIG) 
ELSE COALESCE(udfcur.M_PL_ASSIG2, udfscf.M_PL_ASSIG2) END B_ASG,
CASE 
WHEN trn.M_COMMENT_BS = 'B' THEN
	CASE COALESCE(RTRIM(udfcur.M_PL_ASSIG), RTRIM(udfscf.M_PL_ASSIG))
	WHEN 'ALUMINIUM' THEN 'Aluminium (RM)'
	WHEN 'BITUMEN'   THEN 'Bitumen'
	WHEN 'COAL'      THEN 'Coal'
	WHEN 'COBALT'    THEN 'Cobalt (RM)'
	WHEN 'COPPER'    THEN 'Copper (RM)'
	WHEN 'copper'    THEN 'Copper (RM)'
	WHEN 'FOREX'     THEN 'CED FX Trading'
	WHEN 'FUEL'      THEN 'Fuel'
	WHEN 'GOLD'      THEN 'Gold (RM)'
	WHEN 'IRON ORE'  THEN 'Iron Ore'
	WHEN 'LEAD'      THEN 'Lead (RM)'
	WHEN 'NICKEL'    THEN 'Nickel (RM)'
	WHEN 'SILVER'    THEN 'Silver (RM)'
	WHEN 'SUPRAMAX'  THEN 'Dry Chartering'
	WHEN 'TIN'       THEN 'Tin (RM)'
	WHEN 'ZINC'      THEN 'Zinc (RM)'
	WHEN 'zinc'      THEN 'Zinc (RM)'
	ELSE ' ' END
ELSE
	CASE COALESCE(RTRIM(udfcur.M_PL_ASSIG2), RTRIM(udfscf.M_PL_ASSIG2))
	WHEN 'ALUMINIUM' THEN 'Aluminium (RM)'
	WHEN 'BITUMEN'   THEN 'Bitumen'
	WHEN 'COAL'      THEN 'Coal'
	WHEN 'COBALT'    THEN 'Cobalt (RM)'
	WHEN 'COPPER'    THEN 'Copper (RM)'
	WHEN 'copper'    THEN 'Copper (RM)'
	WHEN 'FOREX'     THEN 'CED FX Trading'
	WHEN 'FUEL'      THEN 'Fuel'
	WHEN 'GOLD'      THEN 'Gold (RM)'
	WHEN 'IRON ORE'  THEN 'Iron Ore'
	WHEN 'LEAD'      THEN 'Lead (RM)'
	WHEN 'NICKEL'    THEN 'Nickel (RM)'
	WHEN 'SILVER'    THEN 'Silver (RM)'
	WHEN 'SUPRAMAX'  THEN 'Dry Chartering'
	WHEN 'TIN'       THEN 'Tin (RM)'
	WHEN 'ZINC'      THEN 'Zinc (RM)'
	WHEN 'zinc'      THEN 'Zinc (RM)'
	ELSE ' ' END
END BA_RMDLAB,
CASE 
WHEN trn.M_COMMENT_BS = 'B' 
THEN
	CASE COALESCE(RTRIM(udfcur.M_PL_ASSIG), RTRIM(udfscf.M_PL_ASSIG))
	WHEN 'ALUMINIUM' THEN '2211'
	WHEN 'BITUMEN'   THEN '1112'
	WHEN 'COAL'      THEN '2311'
	WHEN 'COBALT'    THEN '2220'
	WHEN 'COPPER'    THEN '2213'
	WHEN 'copper'    THEN '2213'
	WHEN 'FOREX'     THEN '2423'
	WHEN 'FUEL'      THEN '1115'
	WHEN 'GOLD'      THEN '2221'
	WHEN 'IRON ORE'  THEN '2313'
	WHEN 'LEAD'      THEN '2214'
	WHEN 'NICKEL'    THEN '2215'
	WHEN 'SILVER'    THEN '2216'
	WHEN 'SUPRAMAX'  THEN '2321'
	WHEN 'TIN'       THEN '2217'
	WHEN 'ZINC'      THEN '2218'
	WHEN 'zinc'      THEN '2218'
	ELSE ' ' END
ELSE
	CASE COALESCE(RTRIM(udfcur.M_PL_ASSIG2), RTRIM(udfscf.M_PL_ASSIG2))
	WHEN 'ALUMINIUM' THEN '2211'
	WHEN 'BITUMEN'   THEN '1112'
	WHEN 'COAL'      THEN '2311'
	WHEN 'COBALT'    THEN '2220'
	WHEN 'COPPER'    THEN '2213'
	WHEN 'copper'    THEN '2213'
	WHEN 'FOREX'     THEN '2423'
	WHEN 'FUEL'      THEN '1115'
	WHEN 'GOLD'      THEN '2221'
	WHEN 'IRON ORE'  THEN '2313'
	WHEN 'LEAD'      THEN '2214'
	WHEN 'NICKEL'    THEN '2215'
	WHEN 'SILVER'    THEN '2216'
	WHEN 'SUPRAMAX'  THEN '2321'
	WHEN 'TIN'       THEN '2217'
	WHEN 'ZINC'      THEN '2218'
	WHEN 'zinc'      THEN '2218'
	ELSE ' ' END
END BA_RMDCOD,
CASE 
WHEN trn.M_COMMENT_BS = 'B' THEN COALESCE(udfcur.M_PL_ASSIG2, udfscf.M_PL_ASSIG2) 
ELSE COALESCE(udfcur.M_PL_ASSIG, udfscf.M_PL_ASSIG) END S_ASG,
CASE 
WHEN trn.M_COMMENT_BS = 'B' THEN
	CASE COALESCE(RTRIM(udfcur.M_PL_ASSIG2), RTRIM(udfscf.M_PL_ASSIG2))
	WHEN 'ALUMINIUM' THEN 'Aluminium (RM)'
	WHEN 'BITUMEN'   THEN 'Bitumen'
	WHEN 'COAL'      THEN 'Coal'
	WHEN 'COBALT'    THEN 'Cobalt (RM)'
	WHEN 'COPPER'    THEN 'Copper (RM)'
	WHEN 'copper'    THEN 'Copper (RM)'
	WHEN 'FOREX'     THEN 'CED FX Trading'
	WHEN 'FUEL'      THEN 'Fuel'
	WHEN 'GOLD'      THEN 'Gold (RM)'
	WHEN 'IRON ORE'  THEN 'Iron Ore'
	WHEN 'LEAD'      THEN 'Lead (RM)'
	WHEN 'NICKEL'    THEN 'Nickel (RM)'
	WHEN 'SILVER'    THEN 'Silver (RM)'
	WHEN 'SUPRAMAX'  THEN 'Dry Chartering'
	WHEN 'TIN'       THEN 'Tin (RM)'
	WHEN 'ZINC'      THEN 'Zinc (RM)'
	WHEN 'zinc'      THEN 'Zinc (RM)'
	ELSE ' ' END
ELSE
	CASE COALESCE(RTRIM(udfcur.M_PL_ASSIG), RTRIM(udfscf.M_PL_ASSIG))
	WHEN 'ALUMINIUM' THEN 'Aluminium (RM)'
	WHEN 'BITUMEN'   THEN 'Bitumen'
	WHEN 'COAL'      THEN 'Coal'
	WHEN 'COBALT'    THEN 'Cobalt (RM)'
	WHEN 'COPPER'    THEN 'Copper (RM)'
	WHEN 'copper'    THEN 'Copper (RM)'
	WHEN 'FOREX'     THEN 'CED FX Trading'
	WHEN 'FUEL'      THEN 'Fuel'
	WHEN 'GOLD'      THEN 'Gold (RM)'
	WHEN 'IRON ORE'  THEN 'Iron Ore'
	WHEN 'LEAD'      THEN 'Lead (RM)'
	WHEN 'NICKEL'    THEN 'Nickel (RM)'
	WHEN 'SILVER'    THEN 'Silver (RM)'
	WHEN 'SUPRAMAX'  THEN 'Dry Chartering'
	WHEN 'TIN'       THEN 'Tin (RM)'
	WHEN 'ZINC'      THEN 'Zinc (RM)'
	WHEN 'zinc'      THEN 'Zinc (RM)'
	ELSE ' ' END
END SA_RMDLAB,
CASE 
WHEN trn.M_COMMENT_BS = 'B' THEN
	CASE COALESCE(RTRIM(udfcur.M_PL_ASSIG2), RTRIM(udfscf.M_PL_ASSIG2))
	WHEN 'ALUMINIUM' THEN '2211'
	WHEN 'BITUMEN'   THEN '1112'
	WHEN 'COAL'      THEN '2311'
	WHEN 'COBALT'    THEN '2220'
	WHEN 'COPPER'    THEN '2213'
	WHEN 'copper'    THEN '2213'
	WHEN 'FOREX'     THEN '2423'
	WHEN 'FUEL'      THEN '1115'
	WHEN 'GOLD'      THEN '2221'
	WHEN 'IRON ORE'  THEN '2313'
	WHEN 'LEAD'      THEN '2214'
	WHEN 'NICKEL'    THEN '2215'
	WHEN 'SILVER'    THEN '2216'
	WHEN 'SUPRAMAX'  THEN '2321'
	WHEN 'TIN'       THEN '2217'
	WHEN 'ZINC'      THEN '2218'
	WHEN 'zinc'      THEN '2218'
	ELSE ' ' END
ELSE
	CASE COALESCE(RTRIM(udfcur.M_PL_ASSIG), RTRIM(udfscf.M_PL_ASSIG))
	WHEN 'ALUMINIUM' THEN '2211'
	WHEN 'BITUMEN'   THEN '1112'
	WHEN 'COAL'      THEN '2311'
	WHEN 'COBALT'    THEN '2220'
	WHEN 'COPPER'    THEN '2213'
	WHEN 'copper'    THEN '2213'
	WHEN 'FOREX'     THEN '2423'
	WHEN 'FUEL'      THEN '1115'
	WHEN 'GOLD'      THEN '2221'
	WHEN 'IRON ORE'  THEN '2313'
	WHEN 'LEAD'      THEN '2214'
	WHEN 'NICKEL'    THEN '2215'
	WHEN 'SILVER'    THEN '2216'
	WHEN 'SUPRAMAX'  THEN '2321'
	WHEN 'TIN'       THEN '2217'
	WHEN 'ZINC'      THEN '2218'
	WHEN 'zinc'      THEN '2218'
	ELSE ' ' END
END SA_RMDCOD,
RTRIM(trn.M_BSECTION)  TRN_BSECCOD,
RTRIM(secb.M_DESC)     TRN_BSECLAB,
RTRIM(trn.M_BSTRATEGY) TRN_BSTG,
RTRIM(trn.M_SSECTION)  TRN_SSECCOD,
RTRIM(secs.M_DESC)     TRN_SSECLAB,
RTRIM(trn.M_SSTRATEGY) TRN_SSTG

FROM TRN_HDR_DBF trn
LEFT JOIN TRN_PFLD_DBF pflb ON RTRIM(trn.M_BPFOLIO) = RTRIM(pflb.M_LABEL)
LEFT JOIN TRN_PFLD_DBF pfls ON RTRIM(trn.M_SPFOLIO) = RTRIM(pfls.M_LABEL)
LEFT JOIN TRN_PFLD_DBF pflsrc ON trn.M_SRC_PFOLIO = pflsrc.M_REF
LEFT JOIN TRN_PFLD_DBF pfldst ON trn.M_DST_PFOLIO = pfldst.M_REF
LEFT JOIN TRN_CPDF_DBF ctp ON trn.M_COUNTRPART = ctp.M_ID
LEFT JOIN TABLE#DATA#PORTFOLI_DBF udfb ON RTRIM(pflb.M_LABEL) = RTRIM(udfb.M_LABEL)
LEFT JOIN TABLE#DATA#PORTFOLI_DBF udfs ON RTRIM(pfls.M_LABEL) = RTRIM(udfs.M_LABEL)
JOIN CONTRACT_DBF cnt ON trn.M_CONTRACT = cnt.M_REFERENCE
LEFT JOIN TRN_EXT_DBF ext ON ( trn.M_NB = ext.M_TRADE_REF AND ( trn.M_TRN_FMLY = 'CURR' OR  trn.M_TRN_FMLY = 'SCF') AND cnt.M_VERSION = ext.M_VERSION )
LEFT JOIN TABLE#DATA#DEALCURR_DBF udfcur ON ext.M_UDF_REF = udfcur.M_NB
LEFT JOIN TABLE#DATA#DEALSCF_DBF udfscf ON ext.M_UDF_REF = udfscf.M_NB
LEFT JOIN TYPOLOGY_DBF typo ON cnt.M_TYPOLOGY = typo.M_REFERENCE
LEFT JOIN TRN_PLIN_DBF plin ON RTRIM(trn.M_INSTRUMENT) = RTRIM(plin.M_REFERENCE)
LEFT JOIN CMT_PLKEY1_DBF plk ON trim(trn.M_PL_KEY1) = TO_CHAR(plk.M_REFERENCE)
LEFT JOIN CM_PHYS_DBF phy ON plk.M_PRODUCT = phy.M_REFERENCE
LEFT JOIN CM_PTYPE_DBF phytyp ON phy.M_TYPE = phytyp.M_REFERENCE
LEFT JOIN UDTB289_DBF phylut ON RTRIM(phy.M_LABEL) = RTRIM(phylut.M_PHYSICAL)
LEFT JOIN TRN_ACSC_DBF secb ON RTRIM(trn.M_BSECTION) = RTRIM(secb.M_LABEL)
LEFT JOIN TRN_ACSC_DBF secs ON RTRIM(trn.M_SSECTION) = RTRIM(secs.M_LABEL)
    -- left join (select trim(M_BODY) from RTG_TYP_DBF where M_LABEL = ' 
    -- MX.ALL.PhysicalProduct'||'_DBF') phylut on rtrim(phy.M_LABEL) = rtrim 
    -- (phylut.M_PHYSICAL)
WHERE 1 = 1
AND trn.M_PURPOSE <> 'MeHzv70053'
AND trn.M_TRN_FMLY IN ('COM', 'CURR', 'IRD', 'SCF')
and rtrim(phy.M_LABEL) in ('PLATINUM', 'PALLADIUM')
-- AND to_char(trn.M_TRN_DATE,'YYYYMMDD') > '2021028'
/*
and trn.M_NB in 
(
10749904,
10764661,
10050175,
15029401
  )
*/
