
select
    TASKNODELIST.WORKFLOW,
    TASKNODELIST.SHEET,
    TASKNODELIST.TASK_NAME AS FROM_TASK,
    TASKNODELIST.TASK_NODE AS FROM_NODE,
    TASKNODELIST.FROM_NODE AS FROM_NODE_ID,
    TASKNODELIST.INPUT_OUTPUT,
    TASKNODELIST.WAITING_ENTRIES,
    TASKLINK.TO_TASK,
    TASKLINK.TO_NODE,
    TASKLINK.FILTER_CODE AS TO_NODE_ID
from
(
    select
        LOGIC.MW_CODE AS PROCESSING_TEMPLATE,
        LOGIC.MW_SUB_CODE AS WORKFLOW,
        SHEET.MW_CODE AS SHEET,
        TASK.TYPE_CODE AS TASK_TYPE,
        TASK.CODE AS TASK_NAME,
        TASKBODY.CODE AS TASK_NODE,
        TASKBODY.INPUT_OUTPUT AS INPUT_OUTPUT,
        TASKBODY.FILTER_CODE AS FROM_NODE,       
        CASE
            WHEN LOGIC.MW_SUB_CODE='Exchange' THEN (SELECT count(*) FROM STPDOC_ENTRY_TABLE WHERE XMLFLOW_STATUS=TASKBODY.FILTER_CODE AND STATUS_TAKEN='N' 
            )
            WHEN LOGIC.MW_SUB_CODE='Contract' THEN (SELECT count(*) FROM STPFC_ENTRY_TABLE WHERE XMLFLOW_STATUS=TASKBODY.FILTER_CODE AND STATUS_TAKEN='N'
            )
            WHEN LOGIC.MW_SUB_CODE='Deliverable' THEN (SELECT count(*) FROM STPDLV_ENTRY_TABLE WHERE XMLFLOW_STATUS=TASKBODY.FILTER_CODE AND STATUS_TAKEN='N'
            )
            WHEN LOGIC.MW_SUB_CODE='Event' THEN (SELECT count(*) FROM STPEVT_ENTRY_TABLE WHERE XMLFLOW_STATUS=TASKBODY.FILTER_CODE AND STATUS_TAKEN='N'
            )
            WHEN LOGIC.MW_SUB_CODE='SI' THEN (SELECT count(*) FROM STPSI_ENTRY_TABLE WHERE XMLFLOW_STATUS=TASKBODY.FILTER_CODE AND STATUS_TAKEN='N'
            )
            WHEN LOGIC.MW_SUB_CODE='AccountingEntry' THEN (SELECT count(*) FROM STPACT_ENTRY_TABLE WHERE XMLFLOW_STATUS=TASKBODY.FILTER_CODE AND STATUS_TAKEN='N' 
            )   
            WHEN LOGIC.MW_SUB_CODE='Excess' THEN (SELECT count(*) FROM STPXSM_ENTRY_TABLE WHERE XMLFLOW_STATUS=TASKBODY.FILTER_CODE AND STATUS_TAKEN='N'
            )   
            WHEN LOGIC.MW_SUB_CODE='MarginCall' THEN (SELECT count(*) FROM STPMCD_ENTRY_TABLE WHERE XMLFLOW_STATUS=TASKBODY.FILTER_CODE AND STATUS_TAKEN='N' 
            )   
            ELSE -1
        END AS WAITING_ENTRIES
    FROM MW_LOGICAL_WORKFLOW_TBL LOGIC, MW_SHEET_TBL SHEET, MXMLEX_TASK_TABLE TASK,MXMLEX_TASK_TABLEBODY TASKBODY
    WHERE LOGIC.MW_ID = SHEET.MW_LOGICAL_WORKFLOW_ID
    AND SHEET.MW_ID = TASK.MW_SHEET_ID
    AND TASK.REFERENCE_ID = TASKBODY.REFERENCE_ID
    AND LOGIC.STATUS_TAKEN = 'N'
    AND SHEET.STATUS_TAKEN = 'N'
    AND TASK.STATUS_TAKEN = 'N'
    AND LOGIC.MW_CODE <> 'Distribution'
    AND SHEET.MW_CODE NOT LIKE 'META_%'
) TASKNODELIST
LEFT OUTER JOIN
(
    select
        LINKS.FROM_TASK,
        LINKS.FROM_NODE,
        LINKS.TO_TASK,
        LINKS.TO_NODE,
        TASKBODY.FILTER_CODE
    from MXMLEX_LINK_TABLE LINKS, MXMLEX_TASK_TABLE TASK,MXMLEX_TASK_TABLEBODY TASKBODY
    WHERE TASK.REFERENCE_ID = TASKBODY.REFERENCE_ID
    AND TASK.STATUS_TAKEN = 'N'
    AND LINKS.STATUS_TAKEN='N'
    AND TASK.CODE=LINKS.TO_TASK
    AND TASKBODY.CODE=LINKS.TO_NODE
) TASKLINK
ON
TASKNODELIST.TASK_NODE = TASKLINK.FROM_NODE
AND TASKNODELIST.TASK_NAME = TASKLINK.FROM_TASK
AND TASKNODELIST.INPUT_OUTPUT='O'
ORDER BY TASKNODELIST.WAITING_ENTRIES asc
