with EOD as (select to_char(EOD_DATE,'yyyy-mm-dd') EOD_DATE, BLOCK_, min(START_TIME) START_, max(END_TIME) END_
, EOD_Date+( decode(TO_CHAR(EOD_DATE,'D'),6,0,7,-1,1) +decode(BLOCK_,'Core Block',1/24 ,'Mercury',2/24 ,'Metal Broker',3/24 ,'CTC',5/24 ,'Accounting',8/24, 'Regulatory',6.5/24
,0))  CUT_OFF
, max(ENDED_STATUS) ENDED_STATUS
, max(RERUN_COUNTER) RERUN_COUNTER, count(1) JOBS_IN_BLOCK_COUNT 
from 
(Select   
to_date(SUBSTR(C.ORDER_DATE,1,4)||'-'||SUBSTR(C.ORDER_DATE,5,2)||'-'||SUBSTR(C.ORDER_DATE,7,2),'yyyy-mm-dd') EOD_Date,
C.JOB_MEM_NAME JOB_NAME, 
case 
when C.JOB_MEM_NAME in ('0000.COM.TOM','Murex_0000','0000.FIXING.CFTOM','BROADCAST_MSG_AND_KILL','MD_COPY_RT_TO_LANA','EOD_ORDER_CANCEL_AMERICA','EVENT_CMSPLIT_ALL','GLOBAL_EXERCIZE_ALL','AUTO_FIX_AMERICA','TG_DM_MAINTENANCE','REP_DATE_REFRESH','REF_PL_FEED_AMERICA','FRONT_MOVE_DATE_AMERICA','FRONT_MOVE_DATE_FOD','RESTART_IMPORTMXML_TASKS','MD_CPY_RT_TO_AP_EM','MD_CPY_RT_TO_RT','LME_3M_UPLOAD','LME_ZERO_PRICE_UNCHECK','MD_CPY_RT_TO_AP_EM2','EOD_EVTTERM_AMERICA','EOD_EVTTERM_APAC','EOD_EVTTERM_EMEA','PROCESSINGCENTER_MOVE_DATE','closingEntityASIA_move_date','closingEntityEMEA_move_date','closingEntityAMERICA_move_date','plcc_move_date') then 'Core Block'
when C.JOB_MEM_NAME in ('MERCURY_INDICIES_EXT','MERCURY_FXG_COM','MERCURY_MTM_302','MERCURY_MTM_200A','MERCURY_CH_300','MERCURY_MTM_300','MERCURY_MTM_200','MERCURY_CH_200','MERCURY_PORTMAP','MERCURY_CH_50','MERCURY_CH_102','MERCURY_CH_201','MERCURY_MTM_102','MERCURY_PTF_UDF','MERCURY_MTM_301','MERCURY_CH_301','MERCURY_METAL_S','MERCURY_MTM_309','MERCURY_UDF','MERCURY_CH_303','MERCURY_CH_200A','MERCURY_MTM_303','MERCURY_CH_302','MERCURY_CH_309','MERCURY_ALM_SEQ','MERCURY_MTM_SEQ','MERCURY_CH_SEQ','MERCURY_PURGE','MERCURY_CH_MTL') then 'Mercury'
when C.JOB_MEM_NAME in ('METAL_BROKER') then 'Metal Broker'
when C.JOB_MEM_NAME in ('TF_CTC_EOD_BF_PS','TF_CTC_CLR_BE_PS','TF_CTC_CONS_BE_PS','TF_CTC_EBRK_BE_PS','TF_CTC_OTC_BE_PS','TF_CTC_OTCW_BE_PS') then 'CTC'
when C.JOB_MEM_NAME in ('ACC_EOD_ALL','TRAF_ALL_ACC','TP_ALL_ACC','ACC_BL_PRG','ALL_ACC_ALT_ID','TRAF_ACC_FIX','TRAF_ACC_STC','ACC_BL_MAP','TRAF_ACC_DLV_BF','TRAF_ACC_FAC_EN','TP_ACC_ALL_DTL','TRAF_ACC_DLV_EX','TRAF_ALL_ACC_EX') then 'Accounting'
when C.JOB_MEM_NAME in ('APAC_REG_BOF_TP','AMERI_REG_BOF_TP','AMERI_REG_BOF_PL','APAC_REG_BOF_MK_STAT','PUMA_REPORT','EMEA_REG_BOF_PL','EMEA_REG_BOF_MK_STAT','APAC_REG_BOF_PL','EMEA_REG_BOF_TP','AMERI_REG_BOF_MK_STA','REG_RPT_D_BOE_EOD_PS','REG_RPT_L_BOE_EOD_PS','QV') then 'Regulatory'
when C.JOB_MEM_NAME in ('') then ''
end Block_, 
  (C.START_TIME) 
,  (C.END_TIME)   , (C.ENDED_STATUS) ENDED_STATUS, (C.RERUN_COUNTER) RERUN_COUNTER
from EMUSER.RUNINFO_HISTORY C   where 1=1 
/*------------------------------          */ and C.START_TIME > sysdate-3 -- to_date('2017-06-22','YYYY-MM-DD') /*------------------------------          */    
and C.SCHED_TABLE='Murex_0000' -- like '%MUREX_0000%'
AND C.JOB_MEM_NAME in (
'0000.COM.TOM','0000.FIXING.CFTOM','BROADCAST_MSG_AND_KILL','MD_COPY_RT_TO_LANA','EOD_ORDER_CANCEL_AMERICA','EVENT_CMSPLIT_ALL','GLOBAL_EXERCIZE_ALL','AUTO_FIX_AMERICA','TG_DM_MAINTENANCE','REP_DATE_REFRESH','REF_PL_FEED_AMERICA','FRONT_MOVE_DATE_AMERICA','FRONT_MOVE_DATE_FOD','RESTART_IMPORTMXML_TASKS','MD_CPY_RT_TO_AP_EM','MD_CPY_RT_TO_RT','LME_3M_UPLOAD','LME_ZERO_PRICE_UNCHECK','MD_CPY_RT_TO_AP_EM2','EOD_EVTTERM_AMERICA','EOD_EVTTERM_APAC','EOD_EVTTERM_EMEA','PROCESSINGCENTER_MOVE_DATE','closingEntityASIA_move_date','closingEntityEMEA_move_date','closingEntityAMERICA_move_date','plcc_move_date'
,'MERCURY_INDICIES_EXT','MERCURY_FXG_COM','MERCURY_MTM_302','MERCURY_MTM_200A','MERCURY_CH_300','MERCURY_MTM_300','MERCURY_MTM_200','MERCURY_CH_200','MERCURY_PORTMAP','MERCURY_CH_50','MERCURY_CH_102','MERCURY_CH_201','MERCURY_MTM_102','MERCURY_PTF_UDF','MERCURY_MTM_301','MERCURY_CH_301','MERCURY_METAL_S','MERCURY_MTM_309','MERCURY_UDF','MERCURY_CH_303','MERCURY_CH_200A','MERCURY_MTM_303','MERCURY_CH_302','MERCURY_CH_309','MERCURY_ALM_SEQ','MERCURY_MTM_SEQ','MERCURY_CH_SEQ','MERCURY_PURGE','MERCURY_CH_MTL'
,'METAL_BROKER'
,'TF_CTC_EOD_BF_PS','TF_CTC_CLR_BE_PS','TF_CTC_CONS_BE_PS','TF_CTC_EBRK_BE_PS','TF_CTC_OTC_BE_PS','TF_CTC_OTCW_BE_PS'
,'ACC_EOD_ALL','TRAF_ALL_ACC','TP_ALL_ACC','ACC_BL_PRG','ALL_ACC_ALT_ID','TRAF_ACC_FIX','TRAF_ACC_STC','ACC_BL_MAP','TRAF_ACC_DLV_BF','TRAF_ACC_FAC_EN','TP_ACC_ALL_DTL','TRAF_ACC_DLV_EX','TRAF_ALL_ACC_EX'
,'APAC_REG_BOF_TP','AMERI_REG_BOF_TP','AMERI_REG_BOF_PL','APAC_REG_BOF_MK_STAT','PUMA_REPORT','EMEA_REG_BOF_PL','EMEA_REG_BOF_MK_STAT','APAC_REG_BOF_PL','EMEA_REG_BOF_TP','AMERI_REG_BOF_MK_STA','REG_RPT_D_BOE_EOD_PS','REG_RPT_L_BOE_EOD_PS','QV'
) ) A group by EOD_DATE, BLOCK_ 
) select 
E.EOD_DATE, E.BLOCK_
, to_char(E.START_,'HH24:MI') Start_
, to_char(E.END_,'HH24:MI') END_
, to_char(E.CUT_OFF,'HH24:MI') CUT_OFF
, case 
when E.END_ - E.CUT_OFF < 1/60/24 then SUBSTR(to_char(to_timestamp(E.END_,'YYYY-MM-DD HH24:MI:SS') - to_timestamp(E.CUT_OFF,'YYYY-MM-DD HH24:MI:SS')),12,5)
when E.END_ - E.CUT_OFF > 1 then '+'||SUBSTR(to_char(to_timestamp(E.END_,'YYYY-MM-DD HH24:MI:SS') - to_timestamp(E.CUT_OFF,'YYYY-MM-DD HH24:MI:SS')),10,7)
else '+'||SUBSTR(to_char(to_timestamp(E.END_,'YYYY-MM-DD HH24:MI:SS') - to_timestamp(E.CUT_OFF,'YYYY-MM-DD HH24:MI:SS')),12,5) end SLA_BUFER
,case when E.CUT_OFF - E.END_ > -31/60/24 /* and ENDED_STATUS=16*/ then 'GREEN' else 'AMBER' end STATUS
, decode(ENDED_STATUS,16,'16 - OK',32,'32 - Error check in GUI!',ENDED_STATUS) ENDED_STATUS_ERROR_CODE
, RERUN_COUNTER, JOBS_IN_BLOCK_COUNT
from EOD E order by E.EOD_DATE,E.START_
;

