DELETE FROM MUREX_DM_OWNER.TRF_PL_HIST_REP
WHERE 
--M_TRADE_NUM=26079853 AND 
    M_REF_DATA IN (112800) AND ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM MUREX_DM_OWNER.TRF_PL_HIST_REP
    WHERE 
    --M_TRADE_NUM=26079853 AND 
    M_REF_DATA IN (112800)
    GROUP BY M_TRADE_NUM, M_PORTFOLIO
); 

COMMIT;